name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP with the version you need
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer

      # Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check Environment Variable
        env:
          DOCUMENT_CLOUD_API_KEY: ${{ secrets.DOCUMENT_CLOUD_API_KEY }}
        run: echo "DOCUMENT_CLOUD_API_KEY=${{ secrets.DOCUMENT_CLOUD_API_KEY }}"

      # Run tests
      - name: Run tests
        env:
          DOCUMENT_CLOUD_API_KEY: ${{ secrets.DOCUMENT_CLOUD_API_KEY }}
        run: vendor/bin/phpunit tests